# Generated by Django 5.2.4 on 2025-07-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='variety',
            field=models.CharField(choices=[('FR', 'France'), ('MAR', 'Maroc'), ('ESP', 'Espagne'), ('IT', 'Italie'), ('TUN', 'Tunisie'), ('TUR', 'Turquie'), ('EGY', 'Egypte')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(through='products.InvoiceItem', to='products.product'),
        ),
    ]
